#!/usr/bin/env bash
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less
if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 1;
fi;

# assign parameters to the variable

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
