#!/usr/bin/env bash
# Configures a Nginx server to listen on port 80 through debugging.

sudo apt-get update
sudo apt-get -y install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
